=== veratech-es/formacion-openehr-desarrolladores/Ejercicio normalizacion/BloodPressure.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="data">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="patient" type="patientType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="patientType">
    <xs:sequence>
      <xs:element name="date" type="xs:string"/>
      <xs:element name="systolic" type="xs:integer"/>
      <xs:element name="diastolic" type="xs:integer"/>
      <xs:element name="position" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="id" use="required" type="xs:integer"/>
  </xs:complexType>
</xs:schema>

=== veratech-es/formacion-openehr-desarrolladores/Ejercicio normalizacion/bloodpressure.xml
<?xml version="1.0" encoding="UTF-8"?>
<data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="bloodpressure.xsd">
    <patient id="000000000000001">
        <date>10/11/2018</date>
        <systolic>95</systolic>
        <diastolic>60</diastolic>
        <position>3</position>
    </patient>
    <patient id="00000000000002">
        <date>03/08/2018</date>
        <systolic>126</systolic>
        <diastolic>87</diastolic>
        <position>0</position>
    </patient>
    <patient id="00000000000003">
        <date>20/09/2020</date>
        <systolic>115</systolic>
        <diastolic>102</diastolic>
        <position>1</position>
    </patient>
</data>
